/**
 * Production Server Script
 *
 * This script sets up a simple Express server to serve the production build artifacts.
 * It serves static files from the '../dist' directory, which is where the production build
 * is generated by Webpack.
 *
 * Usage:
 * This script is typically run via `npm run start-prod` or `yarn run start-prod`.
 * It expects the project to be built first (e.g., via `npm run build`).
 */

const express = require('express');
const path = require('path');

// Initialize Express app
const app = express();

// Configuration
// Use PORT from environment variables or default to 3000
const PORT = process.env.PORT || 3000;
// Directory containing the production build files
const SOURCE_DIR = path.join(__dirname, 'dist');

// Serve static files from the source directory
app.use(express.static(SOURCE_DIR));

// Start the server
app.listen(PORT, () => {
  console.log(`----------------------------------------------------------------`);
  console.log(`🚀 Production Express web server started`);
  console.log(`📡 Listening on: http://localhost:${PORT}`);
  console.log(`wb Serving content from: ${SOURCE_DIR}`);
  console.log(`----------------------------------------------------------------`);
});
